### ISSUE TITLE
вопросы по содержанию

### ISSUE THREAD

**Issue by Densden** [Densden/RPS2#7]
Владимир Юрьевич, вы не знаете нужно ли в введении и исследовательской части писать теорию
например про строение сетей и почему они так строятся, а потом уже переходить к описанию предметной области и т.д.

**Comment by wldmr-key** [comment]
если совсем объема не будет хватать...

**Comment by Densden** [comment]
просто Виктор Олегович говорил что это неплохо бы ему в курсач включить и наверное не очень хорошо будет если в двух курсачах будет одно и то же
